/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export const enum Theme {
  Light = 0,
  Dark = 1
}
export declare function getTheme(): Promise<unknown>
export declare function setTheme(theme: string): Promise<unknown>
